INSERT INTO Track(trackName, country, city, trackLength) VALUES
('Bahrain International Circuit', 'Bahrain', 'Sakhir', 5412),
('Albert Park Grand Prix Circuit', 'Australia', 'Melbourne', 5278),
('Sepang International Circuit', 'Malaysia', 'Kuala Lumpur', 5543),
('Shanghai International Circuit', 'China', 'Shanghai', 5451),
('Circuit de Barcelona-Catalunya', 'Spain', 'Montmeló', 4657),
('Circuit de Monaco', 'Monaco', 'Monte-Carlo', 3337),
('Istanbul Park', 'Turkey', 'Istanbul', 5338),
('Circuit Gilles Villeneuve', 'Canada', 'Montreal', 4361),
('Valencia Street Circuit', 'Spain', 'Valencia', 5419),
('Silverstone Circuit', 'UK', 'Silverstone', 5891),
('Hockenheimring', 'Germany', 'Hockenheim', 4574),
('Hungaroring', 'Hungary', 'Budapest', 4381),
('Circuit de Spa-Francorchamps', 'Belgium', 'Spa', 7004),
('Autodromo Nazionale di Monza', 'Italy', 'Monza', 5793),
('Marina Bay Street Circuit', 'Singapore', 'Marina Bay', 4940),
('Suzuka Circuit', 'Japan', 'Suzuka', 5807),
('Korean International Circuit', 'Korea', 'Yeongam County', 5615),
('Autódromo José Carlos Pace', 'Brazil', 'São Paulo', 4309),
('Yas Marina Circuit', 'UAE', 'Abu Dhabi', 5281),
('Nürburgring', 'Germany', 'Nürburg', 5148),
('Buddh International Circuit', 'India', 'Uttar Pradesh', 5125),
('Circuit of the Americas', 'USA', 'Austin', 5513),
('Red Bull Ring', 'Austria', 'Spielberg', 4318),
('Sochi Autodrom', 'Russia', 'Sochi', 5848),
('Autódromo Hermanos Rodríguez', 'Mexico', 'Mexico City', 4304),
('Baku City Circuit', 'Azerbaijan', 'Baku', 6003),
('Circuit Paul Ricard', 'France', 'Le Castellet', 5842),
('Autodromo Internazionale del Mugello', 'Italy', 'Mugello', 5245),
('Autódromo Internacional do Algarve', 'Portugal', 'Portimão', 4684),
('Autodromo Enzo e Dino Ferrari', 'Italy', 'Imola', 4909),
('Circuit Park Zandvoort', 'Netherlands', 'Zandvoort', 4259),
('Losail International Circuit', 'Qatar', 'Al Daayen', 5419),
('Jeddah Corniche Circuit', 'Saudi Arabia', 'Jeddah', 6174),
('Miami International Autodrome', 'USA', 'Miami', 5412),
('Las Vegas Strip Street Circuit', 'United States', 'Las Vegas', 6201),
