INSERT INTO Team (teamName, nationality, headquarter) VALUES
('Ferrari', 'Italian', 'Maranello, IT'),
('Force India', 'Indian', 'Silverstone, UK'),
('HRT', 'Spanish', 'Murcia, ES'),
('Lotus', 'Malaysian', 'Enstone, UK'),
('McLaren', 'British', 'Woking, UK'),
('Mercedes', 'German', 'Brackley, UK'),
('Red Bull', 'Austrian', 'Milton Keynes, UK'),
('Renault', 'French', 'Enstone, UK'),
('Sauber', 'Swiss', 'Hinwill, SW'),
('Toro Rosso', 'Italian', 'Faenza, IT'),
('Virgin', 'British', 'Dinnington, UK'),
('Williams', 'British', 'Wantage, UK'),
('Caterham', 'Malaysian', 'Leafiled, UK'),
('Lotus F1', 'British', 'Enstone, UK'),
('Marussia', 'Russian', 'Banbury, UK'),
('Manor Marussia', 'British', 'Dinnington, UK'),
('Haas F1 Team', 'American', 'Kannapolis, USA'),
('Alfa Romeo', 'Swiss', 'Arese, IT'),
('Racing Point', 'British', 'Silverstone, UK'),
('AlphaTauri', 'Italian', 'Faenza, IT'),
('Alpine F1 Team', 'French', 'Enstone, UK'),
('Aston Martin', 'British', 'Silverstone, UK'),
('RB F1 Team', 'Italian', 'Faenza, IT')
